GMS/Controllers/ProductsController.cs
using GMS.Mapper;
using GMS_BusinessLogic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Tokens;

namespace GMS.Controllers
{
	public class ProductsController : Controller
	{
		private readonly Product _productRepo = new();

		public IActionResult Index(string productName)
		{
			List<Product> products = MapProfile.dtToProducts(_productRepo.get(productName));
			return View(products);
		}

		// Add
		public IActionResult add() => View(new Product());

		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult add(Product product)
		{
			Product productToCheck = Product.find(product.Name.Trim().ToLower());

			if (productToCheck is not null)
				return BadRequest($"The Product With Name {product.Name} already exist");
			try
			{
				int createdId = _productRepo.add(product);
				return RedirectToAction(nameof(Index));
			}
			catch (Exception e)
			{
				return BadRequest(e.Message);
			}
		}

		//Edit
		public IActionResult edit(int id)
		{
			Product product = Product.find(id);
			if (product is null)
				return NotFound($"Invalid Product Id: {id}");

			return View(product);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult edit(Product product)
		{
			if (product is null)
				return NotFound($"Empty Product");

			Product productToCheck = Product.find(product.Name.Trim().ToLower());

			if (productToCheck is not null && productToCheck.Id != product.Id)
				return BadRequest($"The Product with name {product.Name} already exist");

			Product productToUpdate = Product.find(product.Id);
			productToUpdate.Name = product.Name;
			productToUpdate.Quantity = product.Quantity;

			try
			{
				_productRepo.update(productToUpdate);
				return RedirectToAction(nameof(Index));
			}
			catch (Exception e)
			{
				return BadRequest(e.Message);
			}
		}

		//Delete
		public IActionResult delete(int id)
		{
			Product product = Product.find(id);
			if (product is null)
				return NotFound($"Invalid Product Id: {id}");
			return View(product);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Delete(Product product)
		{
			if (product.Id == 0)
				return BadRequest("Invalid Product Id");

			try
			{
				_productRepo.delete(product.Id);
				return RedirectToAction(nameof(Index));
			}
			catch (Exception e)
			{
				return BadRequest(e.Message);
			}
		}
	}
}

GMS/Controllers/RolesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace GMS.Controllers
{
	[Authorize(Roles = "Admin")]
	public class RolesController : Controller
	{
		private readonly RoleManager<IdentityRole> _roleManager;
		public RolesController(RoleManager<IdentityRole> roleManager) => _roleManager = roleManager;


		public IActionResult Index()
		{
			List<IdentityRole> rolesList = _roleManager.Roles.OrderBy(e => e.Name).ToList();

			return View(rolesList);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> addRole(string roleName)
		{
			if (await _roleManager.RoleExistsAsync(roleName))
				return BadRequest($"The Role {roleName} is already Exists");

			IdentityRole newIdentityRole = new()
			{
				Name = roleName,
				NormalizedName = roleName.ToUpper()
			};

			await _roleManager.CreateAsync(newIdentityRole);
			return RedirectToAction(nameof(Index));
		}


		// Edit Role
		public async Task<IActionResult> Edit(string roleName)
		{
			IdentityRole roleToUpdate = await _roleManager.FindByNameAsync(roleName);

			if (roleToUpdate is null)
				return BadRequest($"The role with name {roleName} is not exists");

			return View(roleToUpdate);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit(IdentityRole identityRole)
		{
			IdentityRole roleToUpdate = await _roleManager.FindByIdAsync(identityRole.Id);

			if (roleToUpdate is null)
				return BadRequest($"The role with name {identityRole.Name} is not exists");


			roleToUpdate.Name = identityRole.Name;
			roleToUpdate.NormalizedName = identityRole.Name.ToUpper();

			await _roleManager.UpdateAsync(roleToUpdate);

			return RedirectToAction(nameof(Index));
		}

		// Delete Role
		public async Task<IActionResult> Delete(string roleName)
		{
			IdentityRole roleToDelete = await _roleManager.FindByNameAsync(roleName);

			if (roleToDelete is null)
				return BadRequest($"The role with name {roleName} is not exists");

			return View(roleToDelete);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		[Authorize(Policy = "onlySuperAdminChecker")]
		public async Task<IActionResult> Delete(IdentityRole identityRole)
		{
			IdentityRole roleToDelete = await _roleManager.FindByIdAsync(identityRole.Id);

			if (roleToDelete is null)
				return BadRequest($"The role with name {identityRole.Name} is not exists");


			await _roleManager.DeleteAsync(roleToDelete);

			return RedirectToAction(nameof(Index));
		}
	}
}

GMS/Controllers/SalesController.cs
using GMS.Mapper;
using GMS.ViewModels;
using GMS_BusinessLogic;
using GMS_BusinessLogic.Categories;
using Microsoft.AspNetCore.Mvc;

namespace GMS.Controllers
{
	public class SalesController : Controller
	{
		private readonly SalesOrder _salesRepo = new();

		public IActionResult Index(string searchString)
		{
			List<SalesIndexViewModel> orders = MapProfile.dtToSalesDetails(_salesRepo.get(searchString));
			return View(orders);
		}

		public IActionResult details(int orderId)
		{
			//List<OrderDetailsViewModel> orderDetails = MapProfile.dtToOrderDetails(_salesRepo.getOrderDetails(orderId));
			//return View(orderDetails);
			return View();
		}

		// Add
		public IActionResult add() => View(new AddClientSaleOrderViewModel());

		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult add(IFormCollection purchaseInvoiceForm)
		{
			return View();
		}

		//Delete
		public IActionResult delete(int orderId)
		{
			Order order = Order.find(orderId);
			return View(order);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult delete(Order order)
		{
			try
			{
				_salesRepo.delete(order.Id);
				return RedirectToAction(nameof(Index));
			}
			catch (Exception e)
			{
				return BadRequest(e.Message);
			}
		}
	}
}

GMS/Controllers/UsersController.cs
using GMS.Mapper;
using GMS_BusinessLogic;
using Microsoft.AspNetCore.Mvc;

namespace GMS.Controllers
{
	public class UsersController : Controller
	{
		private readonly User _UserRepo = new();

		public IActionResult Index(string UserName)
		{
			List<User> Users = MapProfile.dtToUsers(_UserRepo.get(UserName));
			return View(Users);
		}

		// Add
		public IActionResult add() => View(new User());

		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult add(User user)
		{
			int createdId = _UserRepo.add(user);
			if (createdId > 0)
				return RedirectToAction(nameof(Index));
			else
				return BadRequest($"Error in Adding User: {user.UserName}");
		}

		//Edit
		public IActionResult edit(int id)
		{
			User user = GMS_BusinessLogic.User.findByUserId(id);
			if (User is null)
				return NotFound($"Invalid User Id: {id}");

			return View(User);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult edit(User user)
		{
			if (user is null)
				return NotFound($"Empty User");

			User userToUpdate = GMS_BusinessLogic.User.findByUserId(user.Id);

			try
			{
				//userToUpdate = MapProfile.User(UserToUpdate, User);
				_UserRepo.update(userToUpdate);

				return RedirectToAction(nameof(Index));
			}
			catch (Exception e)
			{
				return BadRequest(e.Message);
			}
		}

		//Delete
		public IActionResult delete(int id)
		{
			User User = User.findByUserId(id);
			if (User is null)
				return NotFound($"Invalid User Id: {id}");

			return View(User);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Delete(User user)
		{
			if (!ModelState.IsValid)
				return BadRequest("Invalid User");

			_UserRepo.delete(user.Id);
			return RedirectToAction(nameof(Index));
		}
	}
}

GMS/Views/Shared/_Layout.cshtml
@using GMS.Hellper
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - GMS</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/GMS.styles.css" asp-append-version="true" />
	<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
</head>
<body>
	<header>
		<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
			<div class="container-fluid">
				<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">GMS</a>
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
						aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
					<ul class="navbar-nav flex-grow-1">
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Categories" asp-action="Index">Categories</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index">Products</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Purchases" asp-action="Index">Purchases</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Sales" asp-action="Index">Sales</a>
						</li>
						@if (User.IsInRole(SD.Roles.Admin.ToString()))
						{
							<li class="nav-item">
								<a class="nav-link text-dark" asp-area="" asp-controller="Roles" asp-action="Index">Roles Manager</a>
							</li>

							<li class="nav-item">
								<a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">Users Manager</a>
							</li>
						}
						@* <li>
						<div class="dropdown">
						<button class="btn btn-info dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
						Access Checker End points
						</button>
						<ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
						<li><a class="dropdown-item" asp-controller="AccessChecker" asp-action="allAccess">All Access</a></li>
						<li><a class="dropdown-item" asp-controller="AccessChecker" asp-action="authorizedAccess">Authorized Access</a></li>
						<li><a class="dropdown-item" asp-controller="AccessChecker" asp-action="adminAccess">Admin Access</a></li>
						<li><a class="dropdown-item" asp-controller="AccessChecker" asp-action="userOrAdminAccess">User or Admin Access</a></li>
						<li><a class="dropdown-item" asp-controller="AccessChecker" asp-action="adminAccessWithCreateClaim">Admin Access with Create Claim</a></li>
						<li><a class="dropdown-item" asp-controller="AccessChecker" asp-action="adminAccessWithCreateEditDeleteClaims">Admin Access with Create-Edit-Delete Claims</a></li>
						<li><a class="dropdown-item" asp-controller="AccessChecker" asp-action="userCreateEditDeleteClaimsORAdmin">UserCreateEditDeleteClaims OR Admin</a></li>
						<li><a class="dropdown-item" asp-controller="AccessChecker" asp-action="accountsOver100Days">Accounts Over 100 Days</a></li>
						<li><a class="dropdown-item" asp-controller="AccessChecker" asp-action="adminWithMoreThan1000Days">Admin With More Than 1000 Days</a></li>
						</ul>
						</div>
						</li> *@
					</ul>
					<partial name="_LoginPartialCustom" />
				</div>
			</div>
		</nav>
	</header>
	<div class="container">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	<footer class="border-top footer text-muted">
		<div class="container">
			&copy; 2024 - GMS - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
		</div>
	</footer>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

GMS/Views/Shared/_LoginPartialCustom.cshtml
@using Microsoft.AspNetCore.Identity

@inject SignInManager<ApplicationUser> _signInManager;
@inject UserManager<ApplicationUser> _userManager;


<ul class="navbar-nav">
	@if (_signInManager.IsSignedIn(User))
	{
		<li class="nav-item">
			<a class="nav-link" href="#">Hello @_userManager.GetUserName(User)</a>
		</li>
		<li class="nav-item">
			<form id="logOutForm" method="post" class="form-inline" asp-controller="Account" asp-action="logout">
				<button type="submit" class="btn nav-link">Logout</button>
			</form>
		</li>
	}
	else
	{
		<li class="nav-item">
			<a class="nav-link" asp-controller="Account" asp-action="Register">Register</a>
		</li>
		<li class="nav-item">
			<a class="nav-link" asp-controller="Account" asp-action="Login">Login</a>
		</li>
	}
</ul>